### ISSUE TITLE
Failure on Travis / gcc 4.8.x

### ISSUE THREAD

**Issue by genotrance** [jarikomppa/soloud#206]
> Expected behavior:

Build successfully.

> Actual behavior:

Fails with preprocessor [error](https://travis-ci.org/genotrance/nimterop/jobs/481152438#L2047)

```c
soloud/src/audiosource/wav/dr_flac.h:145:43: error: missing binary operator before token "("
 #elif (defined(__clang__) && __has_feature(attribute_deprecated))
```

> Steps to reproduce the problem:

Build with gcc 4.8.x on Ubuntu (Travis config).

> SoLoud version, operating system, backend used, any other potentially useful information:

Using #head, Ubuntu trusty.

I have tried -std=c++11 but it didn't make a difference.

**Comment by jarikomppa** [comment]
Hi,

If you can reproduce this problem and the fix is simple, could you make a
pull request for the fix?

**Comment by jarikomppa** [comment]
That line doesn't seem to exist in current dr_flac.h, so I assume it has been fixed.
